---
title: "Exploration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Exploration using FinancialModlingR package}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Initialization

## Loading Crop Progress from FinancialModelingR

```{r}
library(FinancialModelingR)
library(readxl)
library(ggplot2)
library(dplyr)
library(corrplot)
data("soybeanCropProgressUSA2017", package = "FinancialModelingR")
soybeanCropProgress2017$WEEK.ENDING <-
  as.Date(soybeanCropProgress2017$WEEK.ENDING, "%Y-%m-%d")
```

## Loading Private Price Data

```{r}
contractsForJuly2020 <- read_price(
  in_file = "private_data/ActiveSoybeanContractsforJuly2020.xlsx", delta_price = T,
  add_delta = T, subset = T, subset_min_date = "2017-01-01",
  rename_price_columns = T, rename_prefix = "july_2020_", skip_lines = 3)
contractsForJuly2020$Date <- as.Date(contractsForJuly2020$Date, "%Y-%m-%d")
print(head(contractsForJuly2020))
```

# Plotting

## Daily Data: Tweets Example

```{r}

```

## Weekly Soybean Crop Progress vs Soybean July 2020 Contract Price

```{r}
plot_price_vs_weekly_series(df1_progress = soybeanCropProgress2017,
                            df2_contracts = contractsForJuly2020) +
  labs(title = "Crop_progress_17 vs March Contract price")
```

## Weekly Soybean Exports vs Soybean July 2020 Contract Price

```{r}
data("soybeanExports", package = "FinancialModelingR")
competitors <- c("ARGENTINA", "BRAZIL")
df_total_export <- soybeanExports %>% group_by(Country) %>%
  summarize(Total_Export = sum(Weekly_Exports, na.rm = T))
top_countries <- head(x = df_total_export$Country[
  order(df_total_export$Total_Export, decreasing = TRUE)], n = 10)
selected_countries <- c(competitors, top_countries)
df_top_export <- soybeanExports[sapply(
  soybeanExports$Country, function(country) country %in% selected_countries), ]
df_top_export <- inner_join(contractsForJuly2020, df_top_export, by = "Date")
ind_col <- c("Weekly_Exports", "CMY_Outstanding_Sales", "CMY_Gross_New_Sales",
             "CMY_Net_Sales" ,"CMY_Total_Commitment")
corr_mat_weekly <- create_corr_plot(
  independent_var_names = ind_col,
  dependent_var_names = colnames(df_top_export)[
    grep("Close",colnames(df_top_export))],
  df = df_top_export,
  selected_countries = selected_countries,
  country_var = "Country",
  remove_countries = c("GRAND TOTAL", "KNOWN"))
```


```{r}
data("soybeanCombinedWASDE")
soybeanWASDE_clean <- clean_wasde(combined_data = soybeanCombinedWASDE)
plot_monthly_data(soybeanWASDE_clean)
```
